lib/code_alchemy_web/router.ex
defmodule CodeAlchemyWeb.Router do
  use CodeAlchemyWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :graphql do
    plug CodeAlchemy.Auth.Pipeline
  end

  if Mix.env == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end

  scope "/", CodeAlchemyWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  scope "/api" do
    pipe_through :graphql

    forward "/", Absinthe.Plug, schema: CodeAlchemyWeb.Schema
  end

  forward "/graphiql", Absinthe.Plug.GraphiQL, schema: CodeAlchemyWeb.Schema

  scope "/auth", CodeAlchemyWeb do
    pipe_through :browser

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
  end
end

lib/code_alchemy_web/views/layout_view.ex
defmodule CodeAlchemyWeb.LayoutView do
  use CodeAlchemyWeb, :view
end

lib/code_alchemy_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>CodeAlchemy · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <ul class="right">
      <%= if @conn.assigns[:user] do %>
        <li>
          Sign Out
        </li>
      <% else %>
        <li>
          <%= link "Github Sign In", to: Routes.auth_path(@conn, :request, "github")%>
        </li>
      <% end%>
    </ul>
    <div id="app"/>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/code_alchemy_web/templates/layout/email.html.eex
<html>
  <head>
    <link rel="stylesheet" href="<%= Routes.static_path(CodeAlchemyWeb.Endpoint, "/css/app.css") %>"/>
  </head>
  <body>
    <div class="container">
      <%= render @view_module, @view_template, assigns %>
    </div>
  </body>
</html>